---
# =====================================================
# Ansible Requirements File
# Defines external collections and roles dependencies
# =====================================================

# 🔹 Collections: Modular namespaces of roles, modules, and plugins
collections:
  # Core Ansible content (recommended baseline)
  - name: ansible.posix
    version: ">=1.5.4"

  # Useful community modules (systemd, networking, etc.)
  - name: community.general
    version: ">=10.3.0"

  # Cloud providers
  - name: amazon.aws
    version: ">=6.5.0"
  - name: google.cloud
    version: ">=1.3.0"
  - name: azure.azcollection
    version: ">=2.6.1"

  # Security and secrets
  - name: community.crypto
    version: ">=2.19.0"

  # Containers / Kubernetes (if needed)
  - name: community.docker
    version: ">=3.12.0"
  - name: kubernetes.core
    version: ">=3.2.0"

# 🔹 External roles: third-party or shared roles from Galaxy or Git
roles:
  # Example: a Git-based private role
  - name: company.devops_baseline
    src: git+https://github.com/company/ansible-role-devops-baseline.git
    version: main
