---


# INBOUND RULES
iptables_application_rules_inbound:
  - description: "Allow tcp inbound ssh from steppingstone"
    iptables_rule: "-A INPUT -s {{ steppingstone_ips | list | join (',') }} -d {{ mgmt0 }} -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

  - description: "Allow tcp inbound ssh from worker, hub and agent nodes"
    iptables_rule: "-A INPUT -s {{ worker_network }},{{ hub_nodes | list | join (',') }},{{ agent_nodes | list | join (',') }},{{ smartxs_network | list | join (',') }} -d {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

  - description: "Allow udp inbound dns from dns_clients"
    iptables_rule: "-A INPUT -s {{ dns_clients | list | join (',') }} -d {{ data0 }} -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT"

  - description: "Allow tcp inbound dns from dns_clients"
    iptables_rule: "-A INPUT -s {{ dns_clients | list | join (',') }} -d {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 53 -j ACCEPT"

  - description: "Allow tcp inbound dhcp from worker and master networks"
    iptables_rule: "-A INPUT -s {{ worker_master_networks | list | join (',') }} -d {{ data0 }} -m state --state NEW -m udp -p udp --dport 67 -j ACCEPT"

  - description: "Allow udp inbound dhcp from worker and master networks"
    iptables_rule: "-A INPUT -s {{ worker_master_networks | list | join (',') }} -d {{ data0 }} -m state --state NEW -m udp -p udp --dport 68 -j ACCEPT"

  - description: "Allow udp inbound ntp from worker and master networks"
    iptables_rule: "-A INPUT -s {{ worker_master_networks | list | join (',') }} -d {{ data0 }} -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT"

  - description: "Allow tcp inbound https from master network and secondary dhcp server"
    iptables_rule: "-A INPUT -s {{ worker_master_networks | list | join (',') }},{{ dhcp_secondary_server }} -d {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT"

  - description: "Allow udp inbound dhcp for HA config"
    iptables_rule: "-A INPUT -s {{ dhcp_secondary_server }} -d {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 647 -j ACCEPT"

  - description: "Allow tcp inbound 3129 from worker and master networks"
    iptables_rule: "-A INPUT -s {{ worker_master_networks | list | join (',') }} -d {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 3129 -j ACCEPT"