---

### GENERIC IPTABLES RULES
iptables_generic_rules_inbound: []
iptables_generic_rules_outbound: []

# INBOUND RULES
iptables_application_rules_inbound:
  - description: "Allow tcp inbound ssh from worker, hub and agent nodes"
    iptables_rule: "-A INPUT -s {{ worker_network }},{{ hub_nodes | list | join (',') }},{{ agent_nodes | list | join (',') }} -d {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

# OUTBOUND RULES
iptables_application_rules_outbound:
  - description: "Allow tcp outbound ssh to worker,master networks and hub nodes"
    iptables_rule: "-A OUTPUT -s {{ data0 }} -d  {{ worker_master_networks | list | join (',') }},{{ hub_nodes | list | join (',') }} -m state --state NEW -m tcp -p tcp --dport 22 -j ACCEPT"

  - description: "Allow udp outbound dns to dns servers"
    iptables_rule: "-A OUTPUT -s {{ data0 }} -d {{ dns_servers | list | join (',') }} -m state --state NEW -m udp -p udp --dport 53 -j ACCEPT"

  - description: "Allow tcp outbound dns to dns servers"
    iptables_rule: "-A OUTPUT -s {{ data0 }} -d {{ dns_servers | list | join (',') }} -m state --state NEW -m tcp -p tcp --dport 53 -j ACCEPT"

  - description: "Allow tcp outbound 443"
    iptables_rule: "-A OUTPUT -s {{ data0 }} -m state --state NEW -m tcp -p tcp --dport 443 -j ACCEPT"

  - description: "Allow tcp outbound ntp to ntp servers"
    iptables_rule: "-A OUTPUT -s {{ data0 }} -d {{ ntp_servers | list | join (',') }} -m state --state NEW -m udp -p udp --dport 123 -j ACCEPT"

...
