---

cert_tool_packages: python3-cryptography
cert_tool_trigger_service: squid

certs_info:
  - cert_type: ejbca_managed
    options:
      cert_force_renewal: "{{ cert_tool_force_renewal | d(false) }}"
      cert_auto_renewal: true
      cert_renewal_period: "+6w"
      cert_update_symlinks: false
      trigger_restart: true
      used_by_service:
        - "{{ cert_tool_trigger_service }}"
    ejbca:
       url: "https://roccaf1p.managedpki.com:8443/ejbca"
       client_cert: "{{ inventory_dir }}/group_vars/all/pki-cert-tool/files/rockclient.crt"
#       client_cert_password: "{{ ejbca_managed_pass }}"
       client_key: "{{ inventory_dir }}/group_vars/all/pki-cert-tool/files/rockclient.key"
       ca: "KPN N.V. Private CA G3"
       validate_certs: false
       cert_profile: "KPN_N.V._Private_CA_G3_TLS_CP"
       end_entity_profile_name: "KPN_N.V._Private_CA_G3_TLS_EE"
       entity_password: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          31666437343633653963623464303966333464656463363766373534393932613938326435343939
          6463376265323137616133636130356534393836383165320a363939616665646361326537616338
          39333666343461363264313066363862373362643537373937306538633063383337613134333834
          6631666437663239660a393537643031626339343336613664623866653132393037663564373037
          62396539633934656438393564326466633430396131333439326139653732656261
#       delegate_to: "{{ eidans_mgmt0 }}"
    attributes:
         cn: "{{ generic_proxy_server }}"
         type: RSA
         size: 4096
         cipher: auto
         entrust_not_after: "+365d"
         key_usage_critical: true
         key_usage:
           - digitalSignature
           - keyEncipherment
           - dataEncipherment
         extended_key_usage_critical: true
         extended_key_usage:
           - clientAuth
           - serverAuth
         subject_alt_name: 
           - "{{ generic_proxy_server }}"
    paths:
      new_cert: "{{ cert_base_path }}/{{ generic_proxy_server }}/{{ ansible_date_time.iso8601_basic_short| replace('-','') }}/{{ generic_proxy_server }}"
      active_cert: "{{ cert_base_path }}/{{ generic_proxy_server }}/{{ generic_proxy_server }}"
      external_signed: "{{ cert_base_path }}/ext_ca/issued/{{ ansible_date_time.iso8601_basic_short| replace('-','') }}"

...
