---

dns_clients:
 - "{{ openshift_service_network }}"
 - "{{ openshift_machine_cidr }}"
 - "{{ master_network }}"
 - "{{ worker_network }}"
 - "{{ hub_nodes[0] }}/32"
 - "{{ hub_nodes[1] }}/32"
 - "{{ smartxs_network[0] }}"
 - "{{ smartxs_network[1] }}"
 - 172.16.4.142 # WINDOWS POC GRADUS
 - 172.16.4.143 # WINDOWS POC GRADUS

# A list of zones and properties per zone.
dns_zones:
  int.cncp.nl:
    primary_ns: ns1.int.cncp.nl
    domain: int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.int.cncp.nl
    hosts:
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"
      proxy: "{{ generic_proxy_server_ip }}"

  kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    domain: kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"
      agent01:
        - "{{ agent_nodes[0] }}"
      haproxy:
        - "{{ hub_nodes[0] }}"
        - "{{ hub_nodes[1] }}"
      hub01:
        - "{{ hub_nodes[0] }}"
      hub02:
        - "{{ hub_nodes[1] }}"
      vcenter:
        - "{{ hub_nodes[0] }}"
        - "{{ hub_nodes[1] }}"
      SU260V0010:
        - 172.16.4.9

  ocp01.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: "{{ openshift_api_vips }}"
      '*.apps': "{{ openshift_ingress_vips }}"
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp04.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.12
      '*.apps': 172.16.2.13
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp05.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.14
      '*.apps': 172.16.2.15
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp06.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.16
      '*.apps': 172.16.2.17
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp07.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.18
      '*.apps': 172.16.2.19
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp08.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.20
      '*.apps': 172.16.2.21
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp09.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.22
      '*.apps': 172.16.2.23
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp10.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.24
      '*.apps': 172.16.2.25
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp11.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.26
      '*.apps': 172.16.2.27
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"

  ocp12.kpn.int.cncp.nl:
    primary_ns: ns1.kpn.int.cncp.nl
    admin_email: admin@kpn.int.cncp.nl
    serial: 2022051501
    secondary_ns: ns2.kpn.int.cncp.nl
    hosts:
      api: 172.16.2.28
      '*.apps': 172.16.2.29
      ns1: "{{ hub_nodes[0] }}"
      ns2: "{{ hub_nodes[1] }}"
...
