---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance
    image: "geerlingguy/docker-ubuntu2404-ansible:latest"
    privileged: true
    pre_build_image: true
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro

provisioner:
  name: ansible
  lint: |
    ansible-lint
  playbooks:
    converge: converge.yml
  inventory:
    hosts:
      all:
        hosts:
          instance:

verifier:
  name: testinfra
  lint: |
    flake8
