---
- name: Ensure base packages are installed
  ansible.builtin.package:
    name: "{{ common_packages }}"
    state: present

- name: Create admin users
  ansible.builtin.user:
    name: "{{ item.name }}"
    uid: "{{ item.uid }}"
    shell: "{{ item.shell }}"
    groups: sudo
    append: yes
    state: present
  loop: "{{ admin_users }}"

- name: Add authorized SSH keys
  ansible.builtin.authorized_key:
    user: "{{ item.name }}"
    key: "{{ item.authorized_keys[0] }}"
  loop: "{{ admin_users }}"

- name: Deploy message of the day
  ansible.builtin.template:
    src: motd.j2
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
  notify:
    - Restart SSH

- name: Disable root SSH login
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^PermitRootLogin'
    line: 'PermitRootLogin no'
    create: no
  notify:
    - Restart SSH
